# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved.
env:
  id: Acrobot-v1
  action_type: discrete
  source_config: {mass_1: 1.0, mass_2: 1.0}
  target_config: {mass_1: 0.1, mass_2: 0.1}
runner:
  max_steps: 500
slbo:
  n_stages: 10
  n_iters: 1
  n_policy_iters: 10
model:
  # model_load_path: /data/ztjiaweixu/Code/Plot/results/slbo/2023011602
  model_load_path: /apdcephfs/share_1150325/ztjiaweixu/slbo/2023011602