# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved.
env:
  id: CartPole-v0
  action_type: discrete
  source_config: {length: 0.5}
  target_config: {length: 0.6}
runner:
  max_steps: 200
  rescale_action: False
common:
  n_stages: 20
  n_iters: 1
  n_policy_iters: 1
model:
  # model_load_path: /data/ztjiaweixu/Code/Plot/results/slbo/2023011602
  model_load_path: /apdcephfs/share_1150325/ztjiaweixu/slbo/2023011602