# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved.
env:
  id: Hopper-v2
  source_config: {version: 'v1'}
  target_config: {version: 'v2'}
runner:
  max_steps: 500
model:
  model_load_path: /data/ztjiaweixu/Code/Plot/results/slbo/2023010904