# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved.
env:
  id: MountainCarContinuous-v0
  source_config: {g: 0.0025}
  target_config: {g: 0.0060}
runner:
  max_steps: 500
slbo:
  n_stages: 20
  n_iters: 1
  n_policy_iters: 10
model:
  model_load_path: /data/ztjiaweixu/Code/Plot/results/slbo/2023011602