# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved.
env:
  id: MountainCarContinuous-v0
  source_config: {g: 0.0025}
  target_config: {g: 0.0060}
runner:
  max_steps: 500
  rescale_action: False
common:
  n_stages: 50
  n_iters: 1 # 2 for mb_ppo
  n_policy_iters: 10
plan:
  n_policy_samples: 2000
model:
  # model_load_path: /data/ztjiaweixu/Code/Plot/results/slbo/2023011602
  model_load_path: /apdcephfs/share_1150325/ztjiaweixu/slbo/2023011602