# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved.
env:
  id: Pendulum-v0
  source_config: {g: 10.0}
  target_config: {g: 3.72}
runner:
  max_steps: 200
  rescale_action: False
common:
  n_stages: 50
  n_iters: 1 # 2 for rpto
PPO:
  n_opt_epochs: 10
  batch_size: 64
  vf_coef: 0.25
  ent_coef: 0.1
  lr: 0.0005
  lr_min: 0.0001
  lr_decay: True
model:
  # model_load_path: /data/ztjiaweixu/Code/Plot/results/slbo/2023011602
  model_load_path: /apdcephfs/share_1150325/ztjiaweixu/slbo/2023011602