# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved.
env:
  id: Pendulum-v0
runner:
  max_steps: 200
PPO:
  n_opt_epochs: 10
  batch_size: 64
  vf_coef: 0.25
  ent_coef: 0.1
  lr: 0.0005
  lr_min: 0.0001
  lr_decay: True
env:
  source_config: {length: 10.0}
  target_config: {length: 3.72}
model:
  model_load_path: None