# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved.
algorithm: PPO
slbo:
  n_stages: 15
  n_iters: 1
  n_policy_iters: 20
rollout:
  n_train_samples: 4000
  n_test_samples: 10000
policy:
  hidden_sizes: [64, 64]
